name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./cmd/cook/

    - name: Tests
      run: if [[ $(find . -name "*_test.go" -type f -exec go test -v $(dirname {}) \; 2>&1 | tee log.txt | grep -c FAIL) -gt 0 ]]; then cat log.txt && exit 1; else cat log.txt; fi

  linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: gofmt
      run: if [ "$(find . -name "*.go" -type f -exec gofmt -l $(dirname {}) \; | wc -l)" -gt 0 ]; then exit 1; fi
