name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build/test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./cmd/cook/

    - name: Tests
      # find each directory containing a *_test.go, 
      # run go test in that folder
      # exit xargs on first failure
      run: find . -type f -name '*_test.go' | sed -r 's|/[^/]+$||' | sort -u | xargs -L1 go test -v $0 || exit 255

  linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: gofmt
      # find each dir containing a .go file
      # run gofmt -s and save failures to a logfile
      # print the logfile if needed and exit failure
    - run: touch err && find . -type f -name '*.go' | sed -r 's|/[^/]+$||' | sort -u | xargs -L1 bash -c 'if [ "$(gofmt -s -l $0 | wc -l)" -gt 0 ]; then gofmt -s -d $0 >> err; fi' && bash -c 'if [ "$(wc -l < bad.txt)" -gt 0 ]; then cat bad.txt; exit 1; fi' 
